SELECT * FROM USERS
SELECT TOP 100 ID, USERNAME_, PASSWORD_, NAMESURNAME, EMAIL, GENDER, BIRTHDATE, CREATEDDATE, TELNR1, TELNR2 FROM USERS

INSERT INTO USERS
(ID, USERNAME_, PASSWORD_, NAMESURNAME, EMAIL, GENDER, BIRTHDATE, CREATEDDATE, TELNR1, TELNR2)
VALUES
(9679, 'KIZBASINA', 'kızkıza777', 'DERNEK', 'KIZBASINA@gmail.com', 'K', '2025-05-01', '2025-05-24', 5323323232, 5323323232)

SELECT * FROM USERS	WHERE ID = 9679	

UPDATE USERS SET NAMESURNAME = 'kız basına' WHERE ID = 9679

DELETE USERS WHERE ID = 9679	

SELECT * FROM USERS WHERE GENDER = 'K'
SELECT * FROM USERS WHERE GENDER <> 'K'
SELECT * FROM USERS WHERE ID >= 7000

SELECT * FROM USERS WHERE ID BETWEEN 10 AND 15

SELECT * FROM USERS WHERE NAMESURNAME LIKE 'YA%'  ---başlayan
SELECT * FROM USERS WHERE NAMESURNAME LIKE '%YA'  ---biten
SELECT * FROM USERS WHERE NAMESURNAME LIKE '%YA%' ---içeren

SELECT * FROM USERS WHERE ID IN (3, 4, 5)
SELECT * FROM USERS WHERE GENDER NOT IN ('K')


UPDATE USERS SET
AGE = DATEDIFF(YEAR, BIRTHDATE, GETDATE())
SELECT * FROM USERS WHERE AGE > 60 AND GENDER = 'E' AND NAMESURNAME LIKE 'ALİ%'

SELECT DISTINCT AGE, GENDER FROM USERS

SELECT * FROM USERS WHERE AGE > 60 AND GENDER = 'E' AND NAMESURNAME LIKE 'ALİ%'
ORDER BY AGE DESC

SELECT TOP 100 * FROM [dbo].[SALEORDERS]

SELECT SUM (LINETOTAL) AS TOTALLINETOTAL FROM SALEORDERS WHERE YEAR_ = 2020

SELECT COUNT (*) AS KAYIT FROM SALEORDERS WHERE YEAR_ = 2020

SELECT MIN (LINETOTAL) FROM SALEORDERS WHERE YEAR_ = 2020
SELECT MAX (LINETOTAL) FROM SALEORDERS WHERE YEAR_ = 2020
SELECT AVG (LINETOTAL) FROM SALEORDERS WHERE YEAR_ = 2020

SELECT SUM (LINETOTAL) AS TOTALLINETOTAL,
MIN (LINETOTAL) AS MINTUTAR,
MAX (LINETOTAL) AS MAXTUTAR,
AVG (LINETOTAL) AS ORTALAMATUTAR
FROM SALEORDERS WHERE YEAR_ = 2020 AND CITY = 'SAMSUN' 

SELECT CITY, BRAND, SUM (LINETOTAL) LINETOTAL FROM SALEORDERS WHERE YEAR_ = 2020
GROUP BY CITY, BRAND ORDER BY LINETOTAL DESC

--- dalin markasının gün bazlı satış adetleri
SELECT
DAYOFWEEK_,
SUM(AMOUNT)AS AMOUNT
FROM SALEORDERS
WHERE BRAND = 'DALIN'
GROUP BY DAYOFWEEK_

--- dalin markasının ürün kategorilerine göre toplam satışlar
SELECT CATEGORY1, CATEGORY2, CATEGORY3, SUM (AMOUNT) AS AMOUNT FROM SALEORDERS
WHERE BRAND = 'DALIN'
GROUP BY CATEGORY1, CATEGORY2, CATEGORY3